Ensure file exists

diff --git a/add-sorted b/add-sorted
--- a/add-sorted
+++ b/add-sorted
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Add entry to sorted list.
-# Copyright (C) 2019 Scott Weldon
+# Copyright (C) 2019-2022 Scott Weldon
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -19,6 +19,12 @@ filename="$1"
 entry="$2"
 details="$3"
 newfile="$filename.new"
+
+if [ ! -e "$filename" ]
+then
+  echo "Error: file '$filename' does not exist."
+  exit 2
+fi
 
 grep --quiet "$entry" "$filename"
 if [ $? -eq 0 ]
