Added ability to skip push/pull part
This is for times like now where my server is down.

diff --git a/gitsync b/gitsync
--- a/gitsync
+++ b/gitsync
@@ -22,37 +22,40 @@ while true
 do
   git commit -a -m "auto-commit at `date`"
 
-  git remote update
-
-  if [ "$?" -eq 0 ]
+  if [ "$1" != "commit-only" ]
   then
-    localCommit=`git rev-parse @`
-    remoteCommit=`git rev-parse @{u}`
-    base=`git merge-base @ @{u}`
+    git remote update
 
-    if [ "$localCommit" == "$remoteCommit" ]
+    if [ "$?" -eq 0 ]
     then
-      echo "Up-to-date"
-    elif [ "$localCommit" == "$base" ]
-    then
-      git pull
-    elif [ "$remoteCommit" == "$base" ]
-    then
-      git push
-    else
-      echo "Local and remote have diverged. Attempting automatic resolution."
-      git pull
-      if [ "$?" -eq 0 ]
+      localCommit=`git rev-parse @`
+      remoteCommit=`git rev-parse @{u}`
+      base=`git merge-base @ @{u}`
+
+      if [ "$localCommit" == "$remoteCommit" ]
       then
-        echo "Successfully resolved."
+        echo "Up-to-date"
+      elif [ "$localCommit" == "$base" ]
+      then
+        git pull
+      elif [ "$remoteCommit" == "$base" ]
+      then
         git push
       else
-        echo -e "\a"
-        break;
+        echo "Local and remote have diverged. Attempting automatic resolution."
+        git pull
+        if [ "$?" -eq 0 ]
+        then
+          echo "Successfully resolved."
+          git push
+        else
+          echo -e "\a"
+          break;
+        fi
       fi
+    else
+      echo "Network error, trying again next time."
     fi
-  else
-    echo "Network error, trying again next time."
   fi
 
   sleep 60
