Add check for error output from `keybase status`
When the disk fills up, `keybase status` gives an error, but doesn't
return an error code.

Appears to be ridiculously complicated, if even possible, to save
stdout and stderr to separate variables, so instead force `jq` command
to fail by just concatenating the (non-JSON) error output.

Can't see easy way to abort calling script entirely, so instead just
sleep indefinitely.  (Username check is only performed once, so sleep
will continue until someone notices.)

diff --git a/kbfs-status b/kbfs-status
--- a/kbfs-status
+++ b/kbfs-status
@@ -19,7 +19,12 @@
 # - jq
 # - keybase
 
-username=$(keybase status --json | jq --raw-output '.Username')
+error_on_username=0
+username=$(keybase status --json 2>&1 | jq --raw-output '.Username')
+if [ $? -ne 0 ]
+then
+  error_on_username=1
+fi
 
 function get_json() {
   jq "$1" "/keybase/private/$username/.kbfs_status"
@@ -37,6 +42,13 @@ function queue_is_empty() {
   then
     echo 'Error getting status, sleeping just in case.'
     return 2
+  fi
+
+  if [ $error_on_username -ne 0 ]
+  then
+    echo 'Error getting username, maybe disk is full?'
+    echo '(FIXME: Should abort/pause, but sleeping indefinitely instead.)'
+    return 3
   fi
 
   if [ $unflushed -eq 0 ]
